FORMAT: 1A
HOST: http://assetapibr.apiblueprint.org/

# asset-api

Asset API is an API to get information about financial assets, such as stock value, 
changes over time, etc.



## Asset Listing [/asset]

All types of assets that someone can posess.

### List All Assets [GET]

+ Response 200 (application/json)
    + Attributes (array[Asset])
    
## Get single asset [/asset/{code}]
+ Request 
    + Parameters
        + code (string) - The uniquely identifying code for the asset

+ Response 200 (application/json)
    + Attributes (Asset)
    
## Asset Types [/asset_type]

Types of assets available.

### List asset types [GET]

+ Response 200 (application/json)
    + Attributes (array[Asset Type])


# Data structures

## Asset (object)
+ code: BR.PETR4 (string)
    Uniquely identifying code for the asset.
    
+ type: stock (string)
    The type of the asset. Must be a type defined in /asset_type

+ currency: BRL (string)
    Currency code based on [ISO 4217](http://www.iso.org/iso/home/standards/currency_codes.htm) currency
    codes.
    
+ unit_value: 201.98 (number)
    Value of a single unit of the asset. TODO: how do we specify precision?
    

## Asset Type (object)
+ type: stock (string)
    The type of the asset.
    
+ description (string)
    A description of the asset type.